### ISSUE TITLE
Slovak Translation branch does not show all translations

### ISSUE THREAD

**Issue by marek-guran** [RaspAP/raspap-webgui#1376]
Hey I have tested the branch: [locale-update/sk_SK](https://github.com/RaspAP/raspap-webgui/tree/locale-update/sk_SK) 

And I found few issues, the website does not show all translations that it should. It replaces some of them with English and I have checked the file messages.po and all English text translations have Slovak translation. It affects everything except: Networking, WireGuard, Authentification. I can send also screenshots if needed.

**Comment by billz** [comment]
Yes, it's true — some UIs such as DHCP settings and System > Reset are missing string definitions in `locale/en_US/messages.po`. This often happens when a new feature PR is merged and gettext strings are added after the fact (or not at all). 

The localization project is ongoing. I can look into adding missing strings and updating the project on Crowdin, but have other PRs to address first.
