### ISSUE TITLE
[Bug]: Default Route on wlan0 after clean install

### ISSUE THREAD

**Issue by assachs** [RaspAP/raspap-webgui#1695]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Issue reporting checklist

- [X] I have read and understand the [issue reporting policy](https://docs.raspap.com/issues/).
- [X] I observed this bug on a clean install of a [supported OS](https://docs.raspap.com/#compatible-operating-systems).
- [X] I have followed the [project prerequisites](https://docs.raspap.com/#quick-start).
- [X] I have searched this repository for existing issues.
- [X] I checked the [FAQ](https://docs.raspap.com/faq/) and [official documentation](https://docs.raspap.com/).
- [X] I am using an [external wireless adapter](https://docs.raspap.com/issues/#external-hardware).
- [X] I have generated a [RaspAP debug log](https://docs.raspap.com/ap-basics/#debug-log) and performed a [self-diagnosis](https://docs.raspap.com/ap-basics/#diagnosing-problems).

### Operating System

Raspberry Pi OS	(64-bit) Lite Bookworm

### Quick install or Manual setup?

Quick install

### Onboard wireless chipset or external adapter?

Onboard wireless chipset

### Hardware

Raspberry Pi 4 Model B

### RaspAP version

3.1.3 (Latest)

### Other software or services running with RaspAP?

No other software

### Bug description

Configuration shown in GUI and real configuration doesn't match after a clean install.

After a clean installation (repeater mode with external WLAN. WLAN 0: internal, AP; WLAN1: external, client) the gui shows "Install a default route for this interface" disabled for wlan0. But a default route is added.  To disable the default route you have to save the DHCP configuration without changing the settings.

Maybe "nogateway" should be added to the provided configuration file.

### Steps to reproduce

Clean installation
Look at networking and DHCP-Server settings. A default route is added, but the option is disabled.

**Comment by billz** [comment]
For clarity, can you post the contents of your `/etc/dhcpcd.conf` ?

**Comment by assachs** [comment]
After the clean install "nogateway" was not in  /etc/dhcpcd.conf (like here: https://github.com/RaspAP/raspap-webgui/blob/master/config/dhcpcd.conf).

But the switch in the GUI was off. After clicking on save, the line with nogateway was added.

Do you need the /etc/dhcpcd.conf file directly after the clean installation?

**Comment by billz** [comment]
Thanks for clarifying. The "Install a default route for this interface" switch will be "off" if one of the following is true:

1. No default route option is defined in dhcpcd.conf
2. The `nogateway` option is present in dhcpcd.conf

Given that `wlan0` is assigned a static IP address and doesn't need a default route for outbound traffic (since the interface is being used for an AP), adding `nogateway` to the default config is appropriate here. This would also simplify configuration of repeater mode for users.

For context, in the absence of this option the Linux kernel will add a default route as described [here](https://docs.raspap.com/repeater/#configure-routing).
